"""
CheXNet Data Loading & Preprocessing
------------------------------------
This script defines the data loading logic for the NIH ChestX-ray14 dataset.
It includes custom dataset classes, hardware acceleration detection (MPS/CPU),
and image transformation pipelines (augmentation for training, resizing for validation).

Features:
- Automated device detection (Prioritizes Apple Silicon MPS).
- Custom PyTorch Dataset for binary classification.
- Grayscale-to-RGB channel expansion (matching DenseNet requirements).
- Standard NIH-dataset normalization.
"""

import os
import torch
from torch.utils.data import Dataset
from PIL import Image
from torchvision import transforms

# --- Hardware Configuration ---

def get_device():
    """
    Detects and returns the best available PyTorch device.
    1. 'mps' for Apple Silicon (MacBooks/Mac Studio).
    2. 'cpu' as a universal fallback.
    """
    if torch.backends.mps.is_available():
        return torch.device('mps')
    return torch.device('cpu')

# --- Custom Dataset Class ---

class ChestXrayDataSet(Dataset):
    """
    PyTorch Dataset for reading binary-labeled Chest X-ray images.
    """
    def __init__(self, data_dir, image_list_file, split='train'):
        """
        Initializes the dataset with image paths and labels.

        Args:
            data_dir (str): Root directory containing the raw image files.
            image_list_file (str): Path to the .txt file generated by build_splits.py.
            split (str): One of 'train', 'val', or 'test'. Influences data augmentation.
        """
        self.data_dir = data_dir
        self.image_names = []
        self.labels = []
        
        # Parse the space-separated list file (Format: image_name label)
        with open(image_list_file, "r") as f:
            for line in f:
                items = line.strip().split()
                if len(items) >= 2:
                    image_name = items[0]
                    label = int(items[1]) # 1 for Pneumonia, 0 for Normal/Other
                    
                    # Store absolute paths for faster loading
                    image_path = os.path.join(data_dir, image_name)
                    self.image_names.append(image_path)
                    self.labels.append(label)

        # ── Image Transformation Pipelines ────────────────────────────────────
        # Standard NIH mean/std for ImageNet-initialized weights
        normalize = transforms.Normalize(mean=[0.485, 0.456, 0.406],
                                         std=[0.229, 0.224, 0.225])

        if split == 'train':
            # Robust augmentation for training to prevent overfitting
            self.transform = transforms.Compose([
                transforms.Grayscale(num_output_channels=3), # Expand 1-channel to 3-channel
                transforms.Resize(256),
                transforms.RandomCrop(224, padding=8),
                transforms.RandomHorizontalFlip(),
                transforms.RandomRotation(5),
                transforms.ToTensor(),
                normalize
            ])
        elif split in ['val', 'test']:
            # Deterministic processing for validation and testing
            self.transform = transforms.Compose([
                transforms.Grayscale(num_output_channels=3),
                transforms.Resize(256),
                transforms.CenterCrop(224),
                transforms.ToTensor(),
                normalize
            ])
        else:
            raise ValueError("split must be 'train', 'val', or 'test'")

    def __getitem__(self, index):
        """
        Loads and transforms an image-label pair.

        Args:
            index (int): Index of the item to retrieve.

        Returns:
            tuple: (Transformed Tensor, Label Tensor)
        """
        image_name = self.image_names[index]
        
        # Load as RGB to ensure compatibility with DenseNet backbone
        image = Image.open(image_name).convert('RGB')
        
        # Apply the split-specific transformation pipeline
        image = self.transform(image)
        
        label = self.labels[index]
        # Return label as a FloatTensor [1] to match BCEWithLogitsLoss expectations
        return image, torch.FloatTensor([label])

    def __len__(self):
        """Returns the total number of samples in the dataset."""
        return len(self.image_names)
